services:
  zola:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1111:1111"
    volumes:
      - .:/project
    working_dir: /project
    command: serve --interface 0.0.0.0 --port 1111
    environment:
      - ZOLA_ENV=development
      
  lab-backend:
    build:
      context: lab-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./lab-backend:/app
      - /app/node_modules 