services:
  zola:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1111:1111"
    volumes:
      - .:/project
    working_dir: /project
    command: serve --interface 0.0.0.0 --port 1111 --base-url "http://localhost:1111"
    environment:
      - ZOLA_ENV=development 