services:
  zola:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    ports:
      - "${PORT:-1111}:${INTERNAL_PORT:-1111}"
    volumes:
      # Mount source for live reloading in development only
      - ${VOLUME_MOUNT:-.:/project}
    working_dir: /project
    command: ${ZOLA_COMMAND:-serve --interface 0.0.0.0 --port 1111}
    environment:
      - ZOLA_ENV=${ZOLA_ENV:-development} 