services:
  zola:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1111:1111"
    volumes:
      - .:/project
    working_dir: /project
    command: serve --interface 0.0.0.0 --port 1111
    environment:
      - ZOLA_ENV=development
      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  lab-backend:
    build:
      context: lab-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./lab-backend:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data: 