services:
  - type: web
    name: peter-lab-backend
    env: node
    region: ohio
    plan: starter
    buildCommand: cd lab-backend && npm install
    startCommand: cd lab-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: peter-lab-redis
          property: connectionString
    healthCheckPath: /health

  - type: keyvalue
    name: peter-lab-redis
    region: ohio
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []