import subprocess
import tempfile
from pathlib import Path

import pytest

from editor import config
from editor.videos import markdown_for, parse_videos, process_video, upload, video_key


def _synthetic_mp4(size="128x96", duration="0.3", with_location=False) -> bytes:
    """A tiny real mp4 generated by ffmpeg itself (no fixture asset needed) --
    same spirit as test_images.py generating a synthetic jpeg with PIL.

    `with_location` writes the same container-level tags a real phone clip
    carries (see scripts/upload-video.py / editor/videos.py's comments on
    -map_metadata -1): TAG:location/location-eng plus the Android device
    tags -- confirmed via ffprobe on real Pixel 10 Pro clips to live only in
    format_tags, never stream_tags.
    """
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "src.mp4"
        cmd = [
            "ffmpeg", "-y", "-v", "error",
            "-f", "lavfi", "-i", f"color=c=blue:s={size}:d={duration}",
            "-c:v", "libx264", "-pix_fmt", "yuv420p",
        ]
        if with_location:
            cmd += [
                "-metadata", "location=+40.7524-73.9125/",
                "-metadata", "location-eng=+40.7524-73.9125/",
                "-metadata", "com.android.model=Pixel 10 Pro",
                "-metadata", "com.android.manufacturer=Google",
            ]
        cmd.append(str(out))
        subprocess.run(cmd, check=True)
        return out.read_bytes()


def _format_tags(data: bytes) -> str:
    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format_tags",
         "-of", "default=noprint_wrappers=0", "-i", "pipe:0"],
        input=data, capture_output=True, check=True,
    )
    return probe.stdout.decode()


# --- process_video ----------------------------------------------------


def test_process_video_scales_to_target_width():
    out = process_video(_synthetic_mp4(size="1280x720"))
    probe = subprocess.run(
        [
            "ffprobe", "-v", "error", "-select_streams", "v:0",
            "-show_entries", "stream=width,height", "-of", "csv=p=0",
            "-i", "pipe:0",
        ],
        input=out, capture_output=True, check=True,
    )
    width, height = probe.stdout.decode().strip().split(",")
    assert int(width) == 640


def test_process_video_strips_audio():
    # Source has no audio track either, but assert the pipeline explicitly
    # drops any input stream that isn't video -- the re-encode uses -an.
    out = process_video(_synthetic_mp4())
    probe = subprocess.run(
        [
            "ffprobe", "-v", "error", "-select_streams", "a",
            "-show_entries", "stream=index", "-of", "csv=p=0",
            "-i", "pipe:0",
        ],
        input=out, capture_output=True,
    )
    assert probe.stdout.decode().strip() == ""


def test_process_video_rejects_garbage_input():
    with pytest.raises(ValueError):
        process_video(b"not actually a video")


def test_process_video_strips_location_and_device_metadata():
    # The privacy hole this whole module exists to close: a phone clip's
    # GPS coordinates (and device model) live in container/format-level
    # metadata, which ffmpeg copies across a re-encode by default unless
    # told not to. This is the video equivalent of test_process_strips_exif
    # in test_images.py.
    src = _synthetic_mp4(with_location=True)
    assert "location" in _format_tags(src)  # sanity: the fixture actually has it

    out = process_video(src)
    tags = _format_tags(out)
    assert "location" not in tags
    assert "com.android.model" not in tags
    assert "com.android.manufacturer" not in tags


# --- video_key ----------------------------------------------------------


def test_video_key_is_descriptive_and_content_addressed():
    data = _synthetic_mp4()
    key = video_key("guerilla-gardening", "Compost Bags", data)
    assert key.startswith("guerilla-gardening/compost-bags-")
    assert key.endswith(".mp4")


def test_video_key_same_bytes_same_key():
    data = _synthetic_mp4()
    assert video_key("p", "a", data) == video_key("p", "a", data)


def test_video_key_without_name_hint_still_works():
    key = video_key("p", "", _synthetic_mp4())
    assert key.startswith("p/")
    assert key.endswith(".mp4")


# --- markdown_for ---------------------------------------------------------


def test_single_video_still_wraps_in_a_row():
    out = markdown_for(
        [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "medium",
    )
    assert out == (
        '<div class="video-row size-medium">\n'
        '<video autoplay loop muted playsinline>\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )


def test_multiple_videos_share_one_row():
    out = markdown_for(
        [
            {"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None},
            {"url": "https://img.cloudy.nyc/p/b.mp4", "sync_loop": None},
        ],
        "small",
    )
    assert out.startswith('<div class="video-row size-small">')
    assert out.rstrip().endswith("</div>")
    assert out.count("<video ") == 2


def test_sync_loop_attribute_is_preserved_when_present():
    out = markdown_for(
        [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": "4"}], "full",
    )
    assert '<video autoplay loop muted playsinline data-sync-loop="4">' in out


def test_markdown_for_rejects_unknown_size():
    with pytest.raises(ValueError):
        markdown_for([{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "huge")


def test_markdown_for_rejects_empty_video_list():
    with pytest.raises(ValueError):
        markdown_for([], "medium")


# --- parse_videos -----------------------------------------------------------


def test_parse_videos_single_clip():
    source = markdown_for(
        [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "medium",
    )
    out = parse_videos("video", source)
    assert out == {
        "size": "medium",
        "side": "none",
        "videos": [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}],
    }


def test_parse_videos_multiple_clips_round_trip():
    source = markdown_for(
        [
            {"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": "4"},
            {"url": "https://img.cloudy.nyc/p/b.mp4", "sync_loop": "4"},
        ],
        "full",
    )
    out = parse_videos("video", source)
    assert out == {
        "size": "full",
        "side": "none",
        "videos": [
            {"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": "4"},
            {"url": "https://img.cloudy.nyc/p/b.mp4", "sync_loop": "4"},
        ],
    }


def test_parse_videos_unknown_kind_returns_none():
    assert parse_videos("paragraph", "Some text.") is None


def test_parse_videos_malformed_returns_none():
    assert parse_videos("video", "not a video row at all") is None
    assert parse_videos("video", "") is None
    assert parse_videos("video", '<div class="video-row size-medium">nothing here</div>') is None


# --- Losslessness: same discipline as parse_images -- a shape the parser
# can't safely reproduce byte-for-byte must return None, not a partial list.


def test_parse_videos_missing_attribute_is_not_lossless():
    source = (
        '<div class="video-row size-medium">\n'
        '<video loop muted playsinline>\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )
    assert parse_videos("video", source) is None


def test_parse_videos_single_quoted_attrs_is_not_lossless():
    source = (
        "<div class=\"video-row size-medium\">\n"
        "<video autoplay loop muted playsinline>\n"
        "<source src='https://img.cloudy.nyc/p/a.mp4' type='video/mp4'>\n"
        "</video>\n"
        "</div>"
    )
    assert parse_videos("video", source) is None


def test_parse_videos_extra_element_in_row_is_not_lossless():
    source = (
        '<div class="video-row size-medium">\n'
        '<div class="caption">Some caption</div>\n'
        '<video autoplay loop muted playsinline>\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )
    assert parse_videos("video", source) is None


def test_parse_videos_missing_size_class_is_not_lossless():
    source = (
        '<div class="video-row">\n'
        '<video autoplay loop muted playsinline>\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )
    assert parse_videos("video", source) is None


def test_parse_videos_no_matching_tags_returns_none_not_empty_list():
    # The critical case, mirroring the img_row test: the row is well-formed
    # but every <video> inside it fails to match (e.g. hand-edited), so a
    # naive parser would find zero clips -- must return None, not [], or the
    # client's Done button would delete an already-populated row.
    source = (
        '<div class="video-row size-medium">\n'
        '<video data-weird="1">\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )
    assert parse_videos("video", source) is None


# --- upload -----------------------------------------------------------------


class FakeS3:
    def __init__(self):
        self.calls = []

    def put_object(self, **kwargs):
        self.calls.append(kwargs)


def test_upload_sets_immutable_cache_headers_and_video_content_type():
    client = FakeS3()
    url = upload(b"bytes", "p/a.mp4", "img.cloudy.nyc", client)

    call = client.calls[0]
    assert call["Bucket"] == "img.cloudy.nyc"
    assert call["Key"] == "p/a.mp4"
    assert call["ContentType"] == "video/mp4"
    assert call["CacheControl"] == "public, max-age=31536000, immutable"
    assert url == "https://img.cloudy.nyc/p/a.mp4"


def test_cli_upload_path_shares_the_content_addressed_key():
    """scripts/upload-video.py used to build its own `<slug>/<name>.mp4` key
    with no content hash, while still setting an immutable Cache-Control --
    re-uploading a fixed clip under the same name reused the URL, so
    Cloudflare's edge and every browser kept serving the old bytes forever.
    It must go through `video_key`, the same as the tablet editor."""
    script = (config.REPO / "scripts" / "upload-video.py").read_text(encoding="utf-8")

    assert "video_key(" in script, "upload-video.py must use the shared content-addressed key"
    assert "f\"{post_slug}/{name}.mp4\"" not in script, "upload-video.py still builds an unhashed key"


# --- `side`: floating a row beside the text that follows it -----------------
# A third class after the size preset. `none` is the default and writes
# nothing at all, so every row published before this feature existed stays
# byte-identical -- the same discipline the size presets already follow.


def test_side_defaults_to_none_and_writes_no_class():
    out = markdown_for([{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "medium")
    assert '<div class="video-row size-medium">' in out


def test_side_right_adds_a_beside_class_after_the_size():
    out = markdown_for(
        [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "medium", "right",
    )
    assert out.startswith('<div class="video-row size-medium beside-right">')


def test_side_left_adds_a_beside_class_after_the_size():
    out = markdown_for(
        [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "small", "left",
    )
    assert out.startswith('<div class="video-row size-small beside-left">')


def test_markdown_for_rejects_unknown_side():
    with pytest.raises(ValueError):
        markdown_for(
            [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "medium", "sideways",
        )


def test_markdown_for_rejects_a_full_width_row_floated_beside_text():
    """A row capped at 100% leaves the text no column to flow into, so the
    combination renders as a plain full-width row with the text pushed
    below it -- an invisible no-op the editor would still show as active.
    Refuse it at the boundary instead.
    """
    with pytest.raises(ValueError):
        markdown_for(
            [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "full", "right",
        )


def test_parse_videos_reads_the_side_back():
    source = markdown_for(
        [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "medium", "right",
    )
    out = parse_videos("video", source)
    assert out == {
        "size": "medium",
        "side": "right",
        "videos": [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}],
    }


def test_parse_videos_reports_no_side_as_none():
    source = markdown_for([{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "medium")
    assert parse_videos("video", source)["side"] == "none"


def test_parse_videos_rejects_an_unknown_beside_class():
    """Not losslessly representable -- `markdown_for` could never emit it,
    so regenerating can't reproduce the source and the caller must fall
    back to editing raw text rather than dropping the class silently.
    """
    source = (
        '<div class="video-row size-medium beside-middle">\n'
        '<video autoplay loop muted playsinline>\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )
    assert parse_videos("video", source) is None
