import subprocess
import tempfile
from pathlib import Path

import pytest

from editor.videos import markdown_for, parse_videos, process_video, upload, video_key


def _synthetic_mp4(size="128x96", duration="0.3") -> bytes:
    """A tiny real mp4 generated by ffmpeg itself (no fixture asset needed) --
    same spirit as test_images.py generating a synthetic jpeg with PIL.
    """
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "src.mp4"
        subprocess.run(
            [
                "ffmpeg", "-y", "-v", "error",
                "-f", "lavfi", "-i", f"color=c=blue:s={size}:d={duration}",
                "-c:v", "libx264", "-pix_fmt", "yuv420p",
                str(out),
            ],
            check=True,
        )
        return out.read_bytes()


# --- process_video ----------------------------------------------------


def test_process_video_scales_to_target_width():
    out = process_video(_synthetic_mp4(size="1280x720"))
    probe = subprocess.run(
        [
            "ffprobe", "-v", "error", "-select_streams", "v:0",
            "-show_entries", "stream=width,height", "-of", "csv=p=0",
            "-i", "pipe:0",
        ],
        input=out, capture_output=True, check=True,
    )
    width, height = probe.stdout.decode().strip().split(",")
    assert int(width) == 640


def test_process_video_strips_audio():
    # Source has no audio track either, but assert the pipeline explicitly
    # drops any input stream that isn't video -- the re-encode uses -an.
    out = process_video(_synthetic_mp4())
    probe = subprocess.run(
        [
            "ffprobe", "-v", "error", "-select_streams", "a",
            "-show_entries", "stream=index", "-of", "csv=p=0",
            "-i", "pipe:0",
        ],
        input=out, capture_output=True,
    )
    assert probe.stdout.decode().strip() == ""


def test_process_video_rejects_garbage_input():
    with pytest.raises(ValueError):
        process_video(b"not actually a video")


# --- video_key ----------------------------------------------------------


def test_video_key_is_descriptive_and_content_addressed():
    data = _synthetic_mp4()
    key = video_key("guerilla-gardening", "Compost Bags", data)
    assert key.startswith("guerilla-gardening/compost-bags-")
    assert key.endswith(".mp4")


def test_video_key_same_bytes_same_key():
    data = _synthetic_mp4()
    assert video_key("p", "a", data) == video_key("p", "a", data)


def test_video_key_without_name_hint_still_works():
    key = video_key("p", "", _synthetic_mp4())
    assert key.startswith("p/")
    assert key.endswith(".mp4")


# --- markdown_for ---------------------------------------------------------


def test_single_video_still_wraps_in_a_row():
    out = markdown_for(
        [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "medium",
    )
    assert out == (
        '<div class="video-row size-medium">\n'
        '<video autoplay loop muted playsinline>\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )


def test_multiple_videos_share_one_row():
    out = markdown_for(
        [
            {"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None},
            {"url": "https://img.cloudy.nyc/p/b.mp4", "sync_loop": None},
        ],
        "small",
    )
    assert out.startswith('<div class="video-row size-small">')
    assert out.rstrip().endswith("</div>")
    assert out.count("<video ") == 2


def test_sync_loop_attribute_is_preserved_when_present():
    out = markdown_for(
        [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": "4"}], "full",
    )
    assert '<video autoplay loop muted playsinline data-sync-loop="4">' in out


def test_markdown_for_rejects_unknown_size():
    with pytest.raises(ValueError):
        markdown_for([{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "huge")


def test_markdown_for_rejects_empty_video_list():
    with pytest.raises(ValueError):
        markdown_for([], "medium")


# --- parse_videos -----------------------------------------------------------


def test_parse_videos_single_clip():
    source = markdown_for(
        [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}], "medium",
    )
    out = parse_videos("video", source)
    assert out == {
        "size": "medium",
        "videos": [{"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": None}],
    }


def test_parse_videos_multiple_clips_round_trip():
    source = markdown_for(
        [
            {"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": "4"},
            {"url": "https://img.cloudy.nyc/p/b.mp4", "sync_loop": "4"},
        ],
        "full",
    )
    out = parse_videos("video", source)
    assert out == {
        "size": "full",
        "videos": [
            {"url": "https://img.cloudy.nyc/p/a.mp4", "sync_loop": "4"},
            {"url": "https://img.cloudy.nyc/p/b.mp4", "sync_loop": "4"},
        ],
    }


def test_parse_videos_unknown_kind_returns_none():
    assert parse_videos("paragraph", "Some text.") is None


def test_parse_videos_malformed_returns_none():
    assert parse_videos("video", "not a video row at all") is None
    assert parse_videos("video", "") is None
    assert parse_videos("video", '<div class="video-row size-medium">nothing here</div>') is None


# --- Losslessness: same discipline as parse_images -- a shape the parser
# can't safely reproduce byte-for-byte must return None, not a partial list.


def test_parse_videos_missing_attribute_is_not_lossless():
    source = (
        '<div class="video-row size-medium">\n'
        '<video loop muted playsinline>\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )
    assert parse_videos("video", source) is None


def test_parse_videos_single_quoted_attrs_is_not_lossless():
    source = (
        "<div class=\"video-row size-medium\">\n"
        "<video autoplay loop muted playsinline>\n"
        "<source src='https://img.cloudy.nyc/p/a.mp4' type='video/mp4'>\n"
        "</video>\n"
        "</div>"
    )
    assert parse_videos("video", source) is None


def test_parse_videos_extra_element_in_row_is_not_lossless():
    source = (
        '<div class="video-row size-medium">\n'
        '<div class="caption">Some caption</div>\n'
        '<video autoplay loop muted playsinline>\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )
    assert parse_videos("video", source) is None


def test_parse_videos_missing_size_class_is_not_lossless():
    source = (
        '<div class="video-row">\n'
        '<video autoplay loop muted playsinline>\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )
    assert parse_videos("video", source) is None


def test_parse_videos_no_matching_tags_returns_none_not_empty_list():
    # The critical case, mirroring the img_row test: the row is well-formed
    # but every <video> inside it fails to match (e.g. hand-edited), so a
    # naive parser would find zero clips -- must return None, not [], or the
    # client's Done button would delete an already-populated row.
    source = (
        '<div class="video-row size-medium">\n'
        '<video data-weird="1">\n'
        '<source src="https://img.cloudy.nyc/p/a.mp4" type="video/mp4">\n'
        '</video>\n'
        '</div>'
    )
    assert parse_videos("video", source) is None


# --- upload -----------------------------------------------------------------


class FakeS3:
    def __init__(self):
        self.calls = []

    def put_object(self, **kwargs):
        self.calls.append(kwargs)


def test_upload_sets_immutable_cache_headers_and_video_content_type():
    client = FakeS3()
    url = upload(b"bytes", "p/a.mp4", "img.cloudy.nyc", client)

    call = client.calls[0]
    assert call["Bucket"] == "img.cloudy.nyc"
    assert call["Key"] == "p/a.mp4"
    assert call["ContentType"] == "video/mp4"
    assert call["CacheControl"] == "public, max-age=31536000, immutable"
    assert url == "https://img.cloudy.nyc/p/a.mp4"
