#!/usr/bin/env bash
# Build the site into public/ atomically.
#
# zola build wipes its output directory first, so building straight into what
# nginx serves means a failed build leaves a half-empty site -- the exact
# failure that pinned 404s in Cloudflare's cache for meetup.astoria.app.
# Build into a scratch dir, then promote only on success.
#
# The zola container runs as the host user (--user) so build output belongs
# to peter, not root -- otherwise cleanup on the *next* build fails trying to
# remove root-owned files (same pattern http-routing uses for cloudflared).
#
# Promotion is an in-place rsync into public/, not a directory swap: nginx's
# bind mount is pinned to public/'s inode at container start, so replacing
# the whole directory (e.g. via mv) leaves a running container serving the
# old, now-orphaned inode until it's force-recreated. Syncing contents into
# the same stable directory means a running container picks up the change
# immediately, with no outage and no recreate.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_URL="${BASE_URL:-https://cloudy.nyc}"
TMP_REL=".build-tmp"
TMP_ABS="$REPO/$TMP_REL"
LEGACY_CONFIG_REL=".build-legacy-config.toml"
LEGACY_CONFIG_ABS="$REPO/$LEGACY_CONFIG_REL"

rm -rf "$TMP_ABS"
rm -f "$LEGACY_CONFIG_ABS"
trap 'rm -f "$LEGACY_CONFIG_ABS"' EXIT

# The container's Zola (editor/zola.Dockerfile, currently pinned to whatever
# Alpine ships) can lag the version CI uses (.github/workflows/deploy.yml,
# currently 0.20.0). Zola 0.19 renamed the feed config keys
# (generate_feed -> generate_feeds, feed_filename -> feed_filenames) and 0.20
# hard-errors on the old singular names (deny_unknown_fields), while anything
# before 0.19 doesn't know the new plural names and just silently produces no
# feed. There's no single key set that satisfies both, so: for a pre-0.19
# container, build from a scratch copy of config.toml with the old keys
# ALSO set (harmless on old Zola, which ignores keys it doesn't recognize) --
# leaving the real, committed config.toml untouched and correct for CI.
ZOLA_VERSION="$(docker run --rm personal-site-zola zola --version | awk '{print $2}')"
ZOLA_MINOR="$(echo "$ZOLA_VERSION" | cut -d. -f2)"
CONFIG_ARGS=()
if [ "$ZOLA_MINOR" -lt 19 ]; then
  echo "container Zola $ZOLA_VERSION predates the 0.19 feed-key rename; building with a legacy-compatible config" >&2
  python3 - "$REPO/config.toml" "$LEGACY_CONFIG_ABS" <<'PY'
import sys, tomllib

src, dst = sys.argv[1], sys.argv[2]
with open(src, "rb") as f:
    cfg = tomllib.load(f)
    text = open(src, encoding="utf-8").read()

extra = []
if "generate_feeds" in cfg:
    extra.append(f"generate_feed = {str(cfg['generate_feeds']).lower()}")
filenames = cfg.get("feed_filenames")
if filenames:
    extra.append(f'feed_filename = "{filenames[0]}"')

# These must land in the ROOT table, same as generate_feeds/feed_filenames.
# Appending at end-of-file would drop them inside whatever [table] header
# (e.g. [extra]) happens to be last, so insert just before the first
# section header instead.
lines = text.splitlines(keepends=True)
insert_at = len(lines)
for i, line in enumerate(lines):
    if line.lstrip().startswith("["):
        insert_at = i
        break

if extra:
    block = ["\n# --- legacy (pre-0.19 Zola) feed keys, generated by build-site.sh ---\n"]
    block += [e + "\n" for e in extra]
    block.append("\n")
    lines[insert_at:insert_at] = block

with open(dst, "w", encoding="utf-8") as f:
    f.writelines(lines)
PY
  CONFIG_ARGS=(--config "/project/$LEGACY_CONFIG_REL")
fi

docker run --rm \
  --user "$(id -u):$(id -g)" \
  -e HOME=/tmp \
  -v "$REPO:/project" \
  -w /project \
  personal-site-zola \
  zola "${CONFIG_ARGS[@]}" build --base-url "$BASE_URL" --output-dir "/project/$TMP_REL" --force

# Refuse to promote a build that produced nothing -- rsync --delete against an
# empty or bogus scratch dir would wipe the live public/ instead of updating it.
if [ ! -s "$TMP_ABS/index.html" ]; then
  echo "build produced no index.html in $TMP_REL -- refusing to sync" >&2
  exit 1
fi

# Promote: sync the new build's contents into the stable public/ dir.
mkdir -p "$REPO/public"
rsync -a --delete "$TMP_ABS/" "$REPO/public/"
rm -rf "$TMP_ABS"

echo "built $REPO/public"
