name: Build Docker image

on:
  push: {}

jobs:

  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      ## AWS

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          mask-aws-account-id: 'no'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.5.3

      - name: Build and push to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deploy/docker/Dockerfile
          push: true
          tags: 265217855447.dkr.ecr.us-east-2.amazonaws.com/test-node-site:${{ github.ref_name }}
          cache-from: type=registry,ref=265217855447.dkr.ecr.us-east-2.amazonaws.com/test-node-site:${{ github.ref_name }}
          cache-to: type=inline

      ## GHCR

      # - name: Login to Github Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push to GHCR
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: deploy/docker/Dockerfile
      #     push: true
      #     tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      #     cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      #     cache-to: type=inline